language: python
  - "3.5"
  - "3.6"

notifications:
  email: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.2
    - g++-5.2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

git:
  submodules: false
  
before_install:
  # C++14 stuff
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # python stuff
  - sudo apt-get install python3-numpy
  - sudo apt-get install libboost-dev
  
install:
  # new gcc
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # python packages
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install --only-binary=numpy numpy
  - python3 -m pip install diversipy
  - python3 -m pip install pybind11
  - python3 setup.py install
  #- CC=gcc-5.2 CXX=g++-5.2 python3 setup.py install

script: 
  - python3 setup.py test