language: python
  - "3.5"
  - "3.6"

notifications:
  email: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.2
    - g++-5.2

git:
  submodules: false
  
before_install:
  - sudo apt-get install python3-numpy
  - sudo apt-get install libboost-dev
  
install:
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install --only-binary=numpy numpy
  - python3 -m pip install diversipy
  - python3 -m pip install pybind11
  - CC=gcc-5.2 CXX=g++-5.2 python3 setup.py install

script: 
  - python3 setup.py test