language: python
  - "3.5"
  - "3.6"

notifications:
  email: false
  
before_install:
  - sudo apt-get install python3-numpy
  - sudo apt-get install libboost-dev
  
install:
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install --only-binary=numpy numpy
  - python3 -m pip install diversipy
  - python3 setup.py install

script: 
  - python3 setup.py test